services:
  reSearch-postgres:
    image: postgres
    container_name: reSearch-postgres
    env_file: ".env"

  reSearch-redis:
    image: redis
    container_name: reSearch-redis
    env_file: ".env"

  reSearch-crawler:
    build: ./crawler
    env_file: ".env"
    deploy:
      replicas: 1

  reSearch-indexer:
    build: ./indexer
    env_file: ".env"
    deploy:
      replicas: 1

  reSearch-tf-idf:
    build: ./tf-idf
    env_file: ".env"
    deploy:
      replicas: 1

  reSearch-page-rank:
    build: ./page-rank
    env_file: ".env"
    deploy:
      replicas: 1

  reSearch-server:
    build: ./server
    env_file: ".env"
    deploy:
      replicas: 1
