server:
  port: "3000"

logging:
  level: "info" # "debug" / "info" / "warn" / "error" / "fatal"
  encoding: "json" # "json" / "console"
  output_paths: # "stderr" / "stdout" / "<absolute/file/path>" / "<relative/file/path>"
    - "stderr"
